RNN are called recurrent because they perform the same task for every element of a sequence
They loop back to themselves, that's called memory.
<br><br>
Sigmoid activation eventually leads to vanishing gradient for "deep" neural nets. 
<br><br>
They are especially important for the first layers, which are responsible for low-level features.
<br><br>
ReLu activation wont work for negative values. ReLu would still end up with vanishing gradients.
<br><br>
Leaky ReLu has a negative derivation for negative values. The zero is not there but small values.
<br><br>
LSTMs introduce a memory pipeline. They solve the problem. Here for RNN, each Neuron is an LSTM cell. 


## 1.1 pyTorch

In [5]:
import torch

In [6]:
# 1-D tensor
a = torch.tensor([2,2,1])
print(a)

tensor([2, 2, 1])


In [7]:
# This is a 2-D 
b = torch.tensor([[2,1,4],[3,5,4],[1,2,0],[4,3,2]])
print(b)

tensor([[2, 1, 4],
        [3, 5, 4],
        [1, 2, 0],
        [4, 3, 2]])


In [8]:
# The size of a tensor
print(a.shape)
print(b.shape)
print(a.size())
print(b.size())

torch.Size([3])
torch.Size([4, 3])
torch.Size([3])
torch.Size([4, 3])


In [9]:
# Get the height/number of rows of b
print(b.shape[0])

4


In [11]:
c = torch.FloatTensor([[2,1,4],[3,5,4],[1,2,0],[4,3,2]])
# c = torch.tensor([1,2,2], dtype = torch.float)
print(c)
print(c.dtype)

tensor([[2., 1., 4.],
        [3., 5., 4.],
        [1., 2., 0.],
        [4., 3., 2.]])
torch.float32


In [13]:
d = torch.DoubleTensor([[2,1,4],[3,5,4],[1,2,0],[4,3,2]])
# c = torch.tensor([1,2,2], dtype = torch.double)
print(d)
print(d.dtype)

tensor([[2., 1., 4.],
        [3., 5., 4.],
        [1., 2., 0.],
        [4., 3., 2.]], dtype=torch.float64)
torch.float64


In [14]:
print(c.mean())
print(c.std())

tensor(2.5833)
tensor(1.5050)


In [15]:
print(d.mean())
print(d.std())

tensor(2.5833, dtype=torch.float64)
tensor(1.5050, dtype=torch.float64)


In [16]:
# Reshape b
# if one dimension is -1, then its size can be inferred
print(b.view(-1, 1))
print(b.view(12))
print(b.view(-1, 4))
print(b.view(3, 4))
b = b.view(-1, 1)
print(b)
print(b.shape)
print()
three_dim = torch.randn(2, 3, 4)
print()
print(three_dim)
print()
print(three_dim.view(2,12))
print()
print(three_dim.view(2,-1))


tensor([[2],
        [1],
        [4],
        [3],
        [5],
        [4],
        [1],
        [2],
        [0],
        [4],
        [3],
        [2]])
tensor([2, 1, 4, 3, 5, 4, 1, 2, 0, 4, 3, 2])
tensor([[2, 1, 4, 3],
        [5, 4, 1, 2],
        [0, 4, 3, 2]])
tensor([[2, 1, 4, 3],
        [5, 4, 1, 2],
        [0, 4, 3, 2]])
tensor([[2],
        [1],
        [4],
        [3],
        [5],
        [4],
        [1],
        [2],
        [0],
        [4],
        [3],
        [2]])
torch.Size([12, 1])


tensor([[[ 0.8538, -0.2597,  0.0159,  1.4274],
         [-1.3282, -1.0005, -0.4853, -0.2711],
         [-0.3444, -0.8514,  1.0216, -0.9478]],

        [[-1.0367,  1.0860, -1.2259,  0.1648],
         [-0.5372,  2.2747, -1.9950, -0.8284],
         [-0.7662,  0.1258, -1.0321,  0.2282]]])

tensor([[ 0.8538, -0.2597,  0.0159,  1.4274, -1.3282, -1.0005, -0.4853, -0.2711,
         -0.3444, -0.8514,  1.0216, -0.9478],
        [-1.0367,  1.0860, -1.2259,  0.1648, -0.5372,  2.2747, -1.9950,

In [17]:
# create a matrix with random numbers taken from a normal distribution with mean 0 and variance 1
r2 = torch.randn(4,4)
print(r2)
print(r2.dtype)

tensor([[-1.4975,  0.2695, -0.5568,  0.2244],
        [ 1.6342, -1.1052,  0.6579,  0.3636],
        [ 1.9898,  1.4924,  1.0597,  1.1917],
        [ 1.5996,  0.2890,  0.4679, -1.1772]])
torch.float32


In [18]:
# create an array of 5 random inteeres from values between 6 and 9
in_array = torch.randint(6,10,(5,))
print(in_array)
print(in_array.dtype)

tensor([8, 6, 8, 9, 9])
torch.int64


In [19]:
# create a 2-D array of size 3x3 filled with random integers from values between 6 and 9
in_array2 = torch.randint(6,10,(3,3))
print(in_array2)

tensor([[8, 8, 7],
        [7, 7, 9],
        [6, 8, 9]])


In [20]:
# get the number of elements
print(torch.numel(in_array))
print(torch.numel(in_array2))

5
9


In [21]:
# construct a 3x3 matrix of zeros and of dtype long:
z = torch.zeros(3,3,dtype=torch.long)
print(z)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [22]:
# construct a 3x3 matrix of ones
o = torch.ones(3,3)
print(o)
print(o.dtype)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
torch.float32


In [23]:
r2_like = torch.randn_like(r2, dtype=torch.double)
print(r2_like)

tensor([[-0.4341, -0.3260, -0.2074,  0.4636],
        [ 1.1431,  0.4302, -1.0535, -0.4648],
        [-0.1443,  0.2746,  0.0434,  1.7762],
        [ 0.6262, -0.6480,  1.0322,  1.0110]], dtype=torch.float64)


In [24]:
# add two tensors, make sure they are the same size and data type
add_result = torch.add(r2_like,r2)
print(add_result)

tensor([[-1.9315, -0.0565, -0.7643,  0.6880],
        [ 2.7772, -0.6750, -0.3956, -0.1012],
        [ 1.8455,  1.7670,  1.1031,  2.9679],
        [ 2.2258, -0.3589,  1.5001, -0.1662]], dtype=torch.float64)


In [25]:
# in place addition, inplace operation
r2.add_(r2_like)
print(r2)

tensor([[-1.9315, -0.0565, -0.7643,  0.6880],
        [ 2.7772, -0.6750, -0.3956, -0.1012],
        [ 1.8455,  1.7670,  1.1031,  2.9679],
        [ 2.2258, -0.3589,  1.5001, -0.1662]])


In [26]:
# matrix slicing
print(r2[:,1])
print(r2[:,:2])
print(r2[:3,:])
num_ten = r2[2,3]
print(num_ten)
print(num_ten.item())
print(r2[2,:])

tensor([-0.0565, -0.6750,  1.7670, -0.3589])
tensor([[-1.9315, -0.0565],
        [ 2.7772, -0.6750],
        [ 1.8455,  1.7670],
        [ 2.2258, -0.3589]])
tensor([[-1.9315, -0.0565, -0.7643,  0.6880],
        [ 2.7772, -0.6750, -0.3956, -0.1012],
        [ 1.8455,  1.7670,  1.1031,  2.9679]])
tensor(2.9679)
2.9679362773895264
tensor([1.8455, 1.7670, 1.1031, 2.9679])


## 1.2 Numpy Bridge

In [27]:
import numpy as np
# Converting a torch tensor to a NumPy Array
a = torch.ones(5)
b = a.numpy()
print(b)

# See how the numpy array changed its value
a.add_(1)
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [28]:
# convert numpy array to torch tensor
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [30]:
# move the tensor to the GPU
r2 = r2.cuda()
print(r2)

tensor([[-1.9315, -0.0565, -0.7643,  0.6880],
        [ 2.7772, -0.6750, -0.3956, -0.1012],
        [ 1.8455,  1.7670,  1.1031,  2.9679],
        [ 2.2258, -0.3589,  1.5001, -0.1662]], device='cuda:0')


In [33]:
CUDA = torch.cuda.is_available()
print(CUDA)
if CUDA:
  add_result = add_result.cuda()
  print(add_result)

True
tensor([[-1.9315, -0.0565, -0.7643,  0.6880],
        [ 2.7772, -0.6750, -0.3956, -0.1012],
        [ 1.8455,  1.7670,  1.1031,  2.9679],
        [ 2.2258, -0.3589,  1.5001, -0.1662]], device='cuda:0',
       dtype=torch.float64)


In [34]:
# convert a list to a tensor
a = [2,3,4,1]
print(a)
to_list = torch.tensor(a)
print(to_list, to_list.dtype)

[2, 3, 4, 1]
tensor([2, 3, 4, 1]) torch.int64


In [35]:
data = [[1.,2.],[3.,4.],[5.,6.],[7.,8.]]
T = torch.tensor(data)
print(T, T.dtype)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]]) torch.float32


## 1.3 Tensor Concatenation

In [39]:
first_1 = torch.randn(2, 5)
print(first_1)
second_1 = torch.randn(3, 5)
print(second_1)
con_1 = torch.cat([first_1, second_1])
print()
print(con_1)
print()
first_2 = torch.randn(2, 3)
second_2 = torch.randn(2, 5)
print(first_2)
print(second_2)
con_2 = torch.cat([first_2, second_2], 1)
print(con_2)

tensor([[ 2.2402,  0.8759,  1.3507,  0.8450, -0.3049],
        [ 1.4476, -0.3003,  1.4400, -1.3726, -0.4726]])
tensor([[ 0.0506,  0.2773,  0.3559,  0.1605, -2.0348],
        [ 0.6059, -0.8921,  1.5359,  1.4607,  0.2283],
        [-0.9125,  0.4059, -0.8976,  0.0282, -1.4525]])

tensor([[ 2.2402,  0.8759,  1.3507,  0.8450, -0.3049],
        [ 1.4476, -0.3003,  1.4400, -1.3726, -0.4726],
        [ 0.0506,  0.2773,  0.3559,  0.1605, -2.0348],
        [ 0.6059, -0.8921,  1.5359,  1.4607,  0.2283],
        [-0.9125,  0.4059, -0.8976,  0.0282, -1.4525]])

tensor([[-0.2715,  1.0697,  0.0429],
        [ 1.4988,  0.9676,  0.0797]])
tensor([[ 1.4400, -0.1160,  0.4265, -0.1904,  1.1431],
        [ 1.5995, -0.5282, -2.9326, -0.0514,  0.4548]])
tensor([[-0.2715,  1.0697,  0.0429,  1.4400, -0.1160,  0.4265, -0.1904,  1.1431],
        [ 1.4988,  0.9676,  0.0797,  1.5995, -0.5282, -2.9326, -0.0514,  0.4548]])


## Adding dimensions to tensor

In [42]:
tensor_1 = torch.tensor([1,2,3,4])
print(tensor_1)
tensor_a = torch.unsqueeze(tensor_1, 0)
print(tensor_a)
print(tensor_a.shape)
tensor_b = torch.unsqueeze(tensor_1, 1)
print(tensor_b)
print(tensor_b.shape)
print()
tensor_2 = torch.rand(2,3,4)
print(tensor_2)
print()
tensor_c = tensor_2[:,:,2]
print(tensor_c)
print(tensor_c.shape)
print()
tensor_d = torch.unsqueeze(tensor_c, 2)
print(tensor_d)
print(tensor_d.shape)

tensor([1, 2, 3, 4])
tensor([[1, 2, 3, 4]])
torch.Size([1, 4])
tensor([[1],
        [2],
        [3],
        [4]])
torch.Size([4, 1])

tensor([[[0.1988, 0.1399, 0.2080, 0.5870],
         [0.1610, 0.9549, 0.8313, 0.7732],
         [0.0596, 0.3250, 0.1525, 0.4258]],

        [[0.7866, 0.7981, 0.6695, 0.3462],
         [0.3172, 0.0087, 0.7764, 0.1006],
         [0.1157, 0.4734, 0.7649, 0.6908]]])

tensor([[0.2080, 0.8313, 0.1525],
        [0.6695, 0.7764, 0.7649]])
torch.Size([2, 3])

tensor([[[0.2080],
         [0.8313],
         [0.1525]],

        [[0.6695],
         [0.7764],
         [0.7649]]])
torch.Size([2, 3, 1])


## 2.1 Building a Chatbot
Code adopted from https://pytorch.org/tutorials/beginner7chatbot_tutorial.html

In [43]:
import torch
import torch.nn as nn
from torch import optim
import torch.nn.functional as F
import csv
import random
import  re
import os
import unicodedata
import codecs
import itertools

In [44]:
CUDA = torch.cuda.is_available()
device = torch.device("cuda" if CUDA else "cpu")

In [46]:
print(device)

cuda


CUDA = torch.cuda.is_available()
print(CUDA)
if CUDA:
  add_result = add_result.cuda()
  print(add_result)