In [1]:
# Uncomment and run the appropriate command for your operating system, if required

# Linux / Binder
!pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# Windows
# !pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# MacOS
# !pip install numpy torch torchvision torchaudio

Looking in links: https://download.pytorch.org/whl/torch_stable.html
     |████████████████████████████████| 159.3 MB 1.3 kB/s eta 0:00:01   |▌                               | 2.4 MB 7.5 MB/s eta 0:00:21     |█                               | 5.2 MB 7.5 MB/s eta 0:00:21     |█▍                              | 7.1 MB 7.5 MB/s eta 0:00:21     |█████▍                          | 26.9 MB 8.2 MB/s eta 0:00:17     |█████▌                          | 27.7 MB 8.2 MB/s eta 0:00:17     |█████████████                   | 65.2 MB 6.1 MB/s eta 0:00:16     |██████████████▉                 | 73.9 MB 7.2 MB/s eta 0:00:12     |█████████████████▌              | 86.9 MB 7.2 MB/s eta 0:00:11     |██████████████████              | 89.9 MB 7.2 MB/s eta 0:00:10     |████████████████████▏           | 100.2 MB 6.3 MB/s eta 0:00:10     |████████████████████▌           | 102.1 MB 6.3 MB/s eta 0:00:10     |████████████████████▉           | 103.6 MB 6.3 MB/s eta 0:00:09     |████████████████████████        | 119.7 MB

In [3]:
# import torch for starters
import torch

# A tensor is a number, vector, matrix, or any n-dimensional array. 
# Let's create a tensor with a single number. 
t1 = torch.tensor(4.)
t1

tensor(4.)

In [6]:
# 4. is shorthand for floating point number, lets verify 
# by checking the dtype attribute ofour tensor
print(t1.dtype)

# now lets create more complex tensors
t2 = torch.tensor([1., 2, 3, 4])
print(t2)

torch.float32
tensor([1., 2., 3., 4.])


In [9]:
# Matrix
t3 = torch.tensor([[5., 6], 
                   [7, 8],
                   [9, 10]])
print(t3)

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])


In [11]:
# 3-dimensional array
t4 = torch.tensor([
    [[11, 12, 13],
     [13, 14, 15]],
    [[15, 16, 17],
     [17., 18., 19.]]])
print(t4)

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])


In [14]:
# lets inspect the shapes
print(t1.shape)
print(t2.shape)
print(t3.shape)
print(t4.shape)

torch.Size([])
torch.Size([4])
torch.Size([3, 2])
torch.Size([2, 2, 3])


In [19]:
# let's compute gradients automatically
# we create three tensors, that are all numbers with a parameter
# requires_grad set to true. Then we create y as a new vector.
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)
y = w * x + b
print(y)

tensor(17., grad_fn=<AddBackward0>)


In [20]:
# lets compute the derivatives, invoke .backward
y.backward()

In [21]:
# now we can display the gradients
print('dy/dx:', x.grad)
print('dy/dw:', w.grad)
print('dy/db:', b.grad)

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)


In [22]:
# tensor manipulation
t6 = torch.full((3,2))

tensor([[42, 42],
        [42, 42],
        [42, 42]])


In [23]:
# concatenate tensors
t7 = torch.cat((t3, t6))
print(t7)

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [42., 42.],
        [42., 42.],
        [42., 42.]])


In [25]:
# change the shape of a tensor
t8 = torch.sin(t7)
t9 = t8.reshape(3, 2, 2)
print(t9)

tensor([[[-0.9589, -0.2794],
         [ 0.6570,  0.9894]],

        [[ 0.4121, -0.5440],
         [-0.9165, -0.9165]],

        [[-0.9165, -0.9165],
         [-0.9165, -0.9165]]])


In [ ]:
# we can try more methods 
# https://pytorch.org/docs/stable/torch.html (delete later in notebook)
# and learn more about numpy from 
# https://jovian.ai/aakashns/python-numerical-computing-with-numpy