## Numpy
#### Array vs. lists

In [1]:
import numpy as np

In [2]:
L = [1,2,3]

In [3]:
A = np.array([1, 2, 3])

In [4]:
for e in L:
    print(e)

1
2
3


In [5]:
for e in A:
    print(e)

1
2
3


In [7]:
L.append(4)
L

[1, 2, 3, 4, 4]

In [8]:
A.append(4)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [9]:
# => The size of a list can change, the size of an array is fit generally speaking

In [10]:
# append 5
L + [5]

[1, 2, 3, 4, 4, 5]

In [13]:
# mathematical operation add a for to each element in A
print(A)
A + [4]

[1 2 3]


array([5, 6, 7])

In [14]:
# add to each element (element-wise)
print(A)
A + np.array([4])

[1 2 3]


array([5, 6, 7])

In [15]:
print(A)
A + np.array([1,2,3])

[1 2 3]


array([2, 4, 6])

In [16]:
# cant add vectors of different sizes
print(A)
A + np.array([1,2])

[1 2 3]


ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [18]:
# repetition
2 * L

[1, 2, 3, 4, 4, 1, 2, 3, 4, 4]

In [20]:
# repetition
L + L

[1, 2, 3, 4, 4, 1, 2, 3, 4, 4]

In [22]:
# Multiply scalar with list
2 * A

array([2, 4, 6])

In [23]:
# add with lists
L2 = []
for e in L: 
    L2.append(e + 3)
L2

[4, 5, 6, 7, 7]

In [26]:
# add with lists with list comprehensions
print(L2)
L2 = [e + 3 for e in L2]
L2

[4, 5, 6, 7, 7]


[7, 8, 9, 10, 10]

In [27]:
print(L)
L2 = []
for e in L: 
    L2.append(e ** 2)
L2

[1, 2, 3, 4, 4]


[1, 4, 9, 16, 16]

In [30]:
# with numpy
np.sqrt(A)

array([1.        , 1.41421356, 1.73205081])

In [31]:
# with numpy
np.log(A)

array([0.        , 0.69314718, 1.09861229])

In [32]:
# => list is a 'handy data structure'
# => numpy array exists specifically to do math

#### dot-product

In [33]:
a = np.array([1,2])
b = np.array([3,4])

In [35]:
# dot product with lists
dot = 0
for e, f in zip(a, b):
    dot += e*f
dot

11

In [36]:
# dot product 
dot = 0
for i in range(len(a)):
    dot += a[i] * b[i]
dot

11

In [37]:
# element wise
a * b

array([3, 8])

In [39]:
# numpy dot
np.sum(a * b)

11

In [40]:
np.dot(a, b)

11

In [41]:
a.dot(b)

11

In [42]:
a@b

11

In [43]:
amag = np.sqrt((a * a).sum())
amag

2.23606797749979

In [44]:
np.linalg.norm(a)

2.23606797749979

In [46]:
cosangle = a.dot(b) / (np.linalg.norm(a) * np.linalg.norm(b))
cosangle

0.9838699100999074

In [48]:
angle_radians = np.arccos(cosangle)
angle_radians

0.17985349979247847

#### speed test

In [50]:
from datetime import datetime

a = np.random.randn(100)
b = np.random.randn(100)
T = 100000

def slow_dot_product(a, b):
    result = 0
    for e, f in zip(a, b):
        result += e*f
    return result

t0 = datetime.now()
for t in range(T):
    slow_dot_product(a, b)
dt1 = datetime.now() - t0

t0 = datetime.now()
for t in range(T):
    a.dot(b)
dt2 = datetime.now() - t0

# how much is dt2 faster than dt1
print('dt1/dt2:', dt1.total_seconds() / dt2.total_seconds())

dt1/dt2: 28.879883337329574


In [51]:
# sometimes it's not easy to avoid for loops

#### matrices


In [52]:
# list matrix, first row then column per convention
L = [[1,2], [3,4]]
L[0]

[1, 2]

In [53]:
L[0][1]

2

In [55]:
# do this in numpy
A = np.array(L)
A

array([[1, 2],
       [3, 4]])

In [56]:
# numpy can do some extra things
A[0][1]

2

In [57]:
# simpler indexing
A[0,1]

2

In [58]:
# simpler to select
A[:,0]

array([1, 3])

In [59]:
# transpose
A.T

array([[1, 3],
       [2, 4]])

In [60]:
np.exp(A)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [61]:
# np converts to a np-array
np.exp(L)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [62]:
# matrix multiplcation
B = np.array([[1,2,3], [4,5,6]])
B

In [63]:
# matrix multiplication
A.dot(B)

array([[ 9, 12, 15],
       [19, 26, 33]])

In [64]:
A@B

array([[ 9, 12, 15],
       [19, 26, 33]])

In [65]:
# determinante
# inaccuracy 
np.linalg.det(A)

-2.0000000000000004

In [66]:
# inverted
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [67]:
# inverse by original should be identity
# inverting a matrix is inaccurate
np.linalg.inv(A).dot(A)

array([[1.0000000e+00, 4.4408921e-16],
       [0.0000000e+00, 1.0000000e+00]])

In [68]:
# trace
np.trace(A)

5

In [69]:
# diagonal
np.diag(A)

array([1, 4])

In [70]:
# diagonal is overloaded
np.diag([1,4])

array([[1, 0],
       [0, 4]])

In [71]:
# eigenvalues
# first array Eigenvalues
# second vectors are Eigenvectors organized in a matrix
np.linalg.eig(A)

(array([-0.37228132,  5.37228132]),
 array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [73]:
# lets check the eigenvectors
# we would expect True and True
Lam, V = np.linalg.eig(A)
V[:, 0] * Lam[0] == A @ V[:, 0]

array([ True, False])

In [74]:
# so this was due to rounding
print(V[:, 0] * Lam[0])
print(A @ V[:, 0])

[ 0.30697009 -0.21062466]
[ 0.30697009 -0.21062466]


In [75]:
np.allclose(V[:, 0] * Lam[0], A @ V[:, 0])

True

In [76]:
# check all eigenvectors and values
np.allclose(V * Lam, A @ V)

True

In [77]:
# use numpy.linalg.eigh for symmetric matrices

#### Solving Linear Systems